version: '3.7'

services:
  web:
    build: .
    command: gunicorn partnerweb_project.wsgi --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - .env

  celery:
    build: .
    command: celery -A partnerweb_project worker --beat -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    container_name: partnerweb3_redis

  db:
    image: postgres
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
