# Generated by Django 2.1.4 on 2019-01-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllAssigned',
            fields=[
                ('address', models.CharField(max_length=1000, unique=True)),
                ('address_id', models.PositiveSmallIntegerField()),
                ('allow_change_status', models.BooleanField()),
                ('allow_schedule', models.BooleanField()),
                ('call_time', models.TimeField()),
                ('comments', models.CharField(max_length=10000)),
                ('date', models.TimeField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('number', models.PositiveSmallIntegerField()),
                ('operator', models.CharField(max_length=255)),
                ('phone1', models.IntegerField()),
                ('phone2', models.IntegerField()),
                ('phone3', models.IntegerField()),
                ('comment_phone1', models.CharField(max_length=255)),
                ('comment_phone2', models.CharField(max_length=255)),
                ('comment_phone3', models.CharField(max_length=255)),
                ('services', models.CharField(max_length=2000)),
                ('shop', models.PositiveSmallIntegerField()),
                ('shop_id', models.PositiveSmallIntegerField()),
                ('status', models.CharField(max_length=255)),
                ('ticket_paired', models.PositiveSmallIntegerField()),
                ('type', models.CharField(max_length=255)),
                ('type_id', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CallToday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, unique=True)),
                ('fio', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('timer', models.CharField(max_length=255)),
                ('workercode', models.IntegerField()),
            ],
        ),
    ]
