# Generated by Django 2.1.4 on 2019-01-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allassigned',
            name='address_id',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='allassigned',
            name='call_time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='allassigned',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
