# Generated by Django 2.1.4 on 2019-01-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beeline', '0002_auto_20190103_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allassigned',
            name='allow_schedule',
            field=models.BooleanField(null=True),
        ),
    ]
