# Generated by Django 2.1.4 on 2019-01-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beeline', '0003_auto_20190103_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allassigned',
            name='allow_change_status',
            field=models.BooleanField(null=True),
        ),
    ]
