# Generated by Django 2.1.4 on 2019-01-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beeline', '0004_auto_20190103_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allassigned',
            name='comment_phone1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='allassigned',
            name='comment_phone2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='allassigned',
            name='comment_phone3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='allassigned',
            name='phone1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='allassigned',
            name='phone2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='allassigned',
            name='phone3',
            field=models.IntegerField(null=True),
        ),
    ]
