# Generated by Django 2.1.4 on 2019-01-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beeline', '0005_auto_20190103_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allassigned',
            name='shop',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='allassigned',
            name='shop_id',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
