# Generated by Django 2.1.4 on 2019-01-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beeline', '0007_auto_20190103_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allassigned',
            name='services',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='allassigned',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='allassigned',
            name='ticket_paired',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='allassigned',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
