# Generated by Django 2.1.4 on 2019-01-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beeline', '0008_auto_20190103_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allassigned',
            name='address',
            field=models.CharField(max_length=1000),
        ),
    ]
