# Generated by Django 2.2 on 2019-09-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
