# Generated by Django 2.2.1 on 2019-12-18 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('positive', models.BooleanField()),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets_handler.Workers')),
            ],
        ),
    ]
