# Generated by Django 2.2 on 2019-09-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_handler', '0003_workers_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
