# Generated by Django 3.0.2 on 2020-02-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_handler', '0004_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
