# Generated by Django 3.0.2 on 2020-02-08 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_handler', '0005_auto_20200208_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='operator',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='tickets_handler.Workers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='operator_password',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
