# Generated by Django 3.0.2 on 2020-02-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_handler', '0006_auto_20200209_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='profile_name',
            field=models.TextField(default='asdf'),
            preserve_default=False,
        ),
    ]
