# Generated by Django 2.2.1 on 2020-02-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_handler', '0009_ticketsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsource',
            name='ticket_number',
            field=models.CharField(max_length=20),
        ),
    ]
