# Generated by Django 2.2.1 on 2020-02-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_handler', '0010_auto_20200216_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsource',
            name='ticket_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
