# Generated by Django 2.2.1 on 2020-02-16 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_handler', '0011_auto_20200216_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsource',
            name='agent',
            field=models.ForeignKey(default=43, on_delete=django.db.models.deletion.CASCADE, to='tickets_handler.Workers'),
            preserve_default=False,
        ),
    ]
