# Generated by Django 2.2.1 on 2020-02-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_handler', '0014_addressdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=70)),
                ('house', models.CharField(max_length=5)),
                ('building', models.CharField(max_length=5)),
                ('category', models.CharField(max_length=20)),
                ('entrance', models.IntegerField(default=None)),
                ('floor', models.IntegerField()),
                ('flats', models.IntegerField()),
            ],
        ),
    ]
