# Generated by Django 2.2.1 on 2020-02-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_handler', '0015_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='category',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
