# Generated by Django 2.2.1 on 2020-02-22 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_handler', '0016_auto_20200222_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntranceImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('date_load', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailBoxImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('date_load', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='addressdata',
            name='entrance',
        ),
        migrations.RemoveField(
            model_name='addressdata',
            name='flats',
        ),
        migrations.RemoveField(
            model_name='addressdata',
            name='flats_img',
        ),
        migrations.AddField(
            model_name='addressdata',
            name='date_start',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='addressdata',
            name='promouter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tickets_handler.Promouter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promouter',
            name='date_hired',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='addressdata',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets_handler.Address'),
        ),
        migrations.AlterField(
            model_name='addressdata',
            name='entrance_img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets_handler.EntranceImg'),
        ),
        migrations.AddField(
            model_name='addressdata',
            name='mailbox_img',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tickets_handler.MailBoxImg'),
            preserve_default=False,
        ),
    ]
