# Generated by Django 2.2.1 on 2020-02-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_handler', '0017_auto_20200222_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressdata',
            name='entrance_img',
        ),
        migrations.AddField(
            model_name='addressdata',
            name='entrance_img',
            field=models.ManyToManyField(to='tickets_handler.EntranceImg'),
        ),
        migrations.RemoveField(
            model_name='addressdata',
            name='mailbox_img',
        ),
        migrations.AddField(
            model_name='addressdata',
            name='mailbox_img',
            field=models.ManyToManyField(to='tickets_handler.MailBoxImg'),
        ),
    ]
