# Generated by Django 2.2.1 on 2020-02-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_handler', '0018_auto_20200222_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='Архангельск', max_length=50),
            preserve_default=False,
        ),
    ]
