# Generated by Django 2.2.1 on 2020-02-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_handler', '0019_address_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsource',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workers',
            name='hiring_date',
            field=models.DateField(auto_now=True),
        ),
    ]
