# Generated by Django 2.2.1 on 2020-02-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_handler', '0021_auto_20200223_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresstodo',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
