# Generated by Django 2.2.1 on 2020-02-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_handler', '0022_addresstodo_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTariffPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_name', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('segment', models.CharField(max_length=10)),
            ],
        ),
    ]
