# Generated by Django 2.2.1 on 2020-03-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_handler', '0023_tickettariffprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketTariffPrice',
        ),
        migrations.AddField(
            model_name='additionalticket',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
