# Generated by Django 2.2.1 on 2020-03-31 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_handler', '0026_auto_20200320_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressdata',
            name='address',
        ),
        migrations.RemoveField(
            model_name='addressdata',
            name='entrance_img',
        ),
        migrations.RemoveField(
            model_name='addressdata',
            name='mailbox_img',
        ),
        migrations.RemoveField(
            model_name='addressdata',
            name='promouter',
        ),
        migrations.RemoveField(
            model_name='addresstodo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='addresstodo',
            name='to_promouter',
        ),
        migrations.RemoveField(
            model_name='promouter',
            name='area',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='AddressData',
        ),
        migrations.DeleteModel(
            name='AddressToDo',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='EntranceImg',
        ),
        migrations.DeleteModel(
            name='MailBoxImg',
        ),
        migrations.DeleteModel(
            name='Promouter',
        ),
    ]
