# Generated by Django 2.2.1 on 2020-03-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_handler', '0027_auto_20200331_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiefInstaller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, unique=True)),
                ('number', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
