# Generated by Django 2.2.1 on 2020-05-19 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_handler', '0028_chiefinstaller'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedTickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.IntegerField()),
                ('when_assigned', models.DateTimeField()),
                ('client_address', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=150)),
                ('phones', models.CharField(max_length=150)),
                ('assigned_date', models.DateTimeField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets_handler.Workers')),
            ],
        ),
        migrations.DeleteModel(
            name='TicketPrice',
        ),
    ]
