# Generated by Django 2.2.1 on 2020-06-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_handler', '0030_aup'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='supervisor_password',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
