# Generated by Django 2.2.13 on 2020-08-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_handler', '0031_employer_supervisor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtickets',
            name='when_assigned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
