# Generated by Django 2.2.13 on 2020-09-11 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_handler', '0033_firebasenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebasenotification',
            name='last_call_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firebasenotification',
            name='today_count_notification',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='firebasenotification',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets_handler.Workers'),
        ),
    ]
