# Generated by Django 2.2.13 on 2020-09-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_handler', '0034_auto_20200912_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebasenotification',
            name='ticket_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
