# Generated by Django 3.1 on 2020-09-29 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_handler', '0035_firebasenotification_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtickets',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets_handler.workers'),
        ),
    ]
