# Generated by Django 2.2.1 on 2019-12-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='phone',
            field=models.TextField(),
        ),
    ]
