# Generated by Django 2.2.1 on 2019-12-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0002_auto_20191221_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='called',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
