# Generated by Django 2.2.1 on 2019-12-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0003_subscribers_called'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='call_time',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscribers',
            name='status_result',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
