# Generated by Django 2.2.1 on 2020-03-31 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets_handler', '0028_chiefinstaller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=70)),
                ('house', models.CharField(max_length=5)),
                ('building', models.CharField(blank=True, max_length=5, null=True)),
                ('entrance', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('flats', models.IntegerField()),
                ('area_alias', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('chief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets_handler.ChiefInstaller')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EntranceImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('date_load', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MailBoxImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('date_load', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promouter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=2)),
                ('date_hired', models.DateField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='territory.Area')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='territory.City'),
        ),
        migrations.CreateModel(
            name='AddressToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(auto_now=True)),
                ('done', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='territory.Address')),
                ('to_promouter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='territory.Promouter')),
            ],
        ),
        migrations.CreateModel(
            name='AddressData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='territory.AddressToDo')),
                ('entrance_img', models.ManyToManyField(to='territory.EntranceImg')),
                ('mailbox_img', models.ManyToManyField(to='territory.MailBoxImg')),
                ('promouter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='territory.Promouter')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='territory.Area'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='territory.City'),
        ),
        migrations.AddField(
            model_name='address',
            name='global_problems',
            field=models.ManyToManyField(to='territory.GlobalProblem'),
        ),
        migrations.AddField(
            model_name='address',
            name='master',
            field=models.ManyToManyField(to='tickets_handler.Workers'),
        ),
    ]
