# Generated by Django 2.2.1 on 2020-06-07 19:39

from django.db import migrations, models
import partnerweb_project.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0004_auto_20200607_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entranceimg',
            name='img',
            field=models.ImageField(storage=partnerweb_project.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='mailboximg',
            name='img',
            field=models.ImageField(storage=partnerweb_project.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
    ]
