# Generated by Django 2.2.1 on 2020-06-08 11:00

from django.db import migrations
import django_resized.forms
import partnerweb_project.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0005_auto_20200607_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entranceimg',
            name='img',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[720, 1080], storage=partnerweb_project.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='mailboximg',
            name='img',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[720, 1080], storage=partnerweb_project.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
