# Generated by Django 2.2.1 on 2020-06-17 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0006_auto_20200608_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='promouter',
            name='price_to_paper',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PromouterPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField()),
                ('promouter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='territory.Promouter')),
            ],
        ),
    ]
