# Generated by Django 2.2.1 on 2020-06-17 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_handler', '0031_employer_supervisor_password'),
        ('territory', '0007_auto_20200617_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='promouter',
            name='bank_detail',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promouter',
            name='master',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='tickets_handler.AUP'),
            preserve_default=False,
        ),
    ]
