# Generated by Django 2.2.1 on 2020-06-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0008_auto_20200617_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promouter',
            name='bank_detail',
            field=models.CharField(max_length=30),
        ),
    ]
