# Generated by Django 2.2.1 on 2019-11-13 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets_handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IS_INAC_PRESET_id', models.CharField(blank=True, max_length=100, null=True)),
                ('IS_INAC_PRESET_name', models.CharField(blank=True, max_length=250, null=True)),
                ('IS_PRESET_id', models.CharField(blank=True, max_length=100, null=True)),
                ('IS_PRESET_name', models.CharField(blank=True, max_length=250, null=True)),
                ('VPDN_id', models.CharField(blank=True, max_length=100, null=True)),
                ('VPDN_name', models.CharField(blank=True, max_length=250, null=True)),
                ('IPTV_id', models.CharField(blank=True, max_length=100, null=True)),
                ('IPTV_name', models.CharField(blank=True, max_length=250, null=True)),
                ('TVE_id', models.CharField(blank=True, max_length=100, null=True)),
                ('TVE_name', models.CharField(blank=True, max_length=250, null=True)),
                ('W_NONSTOP_id', models.CharField(blank=True, max_length=100, null=True)),
                ('W_NONSTOP_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('ticket_paired', models.PositiveIntegerField()),
                ('address_id', models.PositiveIntegerField(unique=True)),
                ('status', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets_handler.Workers')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistic.Services')),
            ],
        ),
        migrations.CreateModel(
            name='MonthReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('week', models.DateField()),
                ('switch', models.IntegerField()),
                ('assign', models.IntegerField()),
                ('created', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets_handler.Workers')),
            ],
        ),
    ]
