from django.db import models
class AllAssigned(models.Model):
    address = models.CharField(max_length=1000)
    address_id = models.PositiveSmallIntegerField(null=True)
    allow_change_status = models.BooleanField(null=True)
    allow_schedule = models.BooleanField(null=True)
    call_time = models.CharField(max_length=255,null=True)
    comments = models.CharField(max_length=10000)
    date = models.CharField(max_length=255)
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    number = models.PositiveSmallIntegerField()
    operator = models.CharField(max_length=255)
    phone1 = models.IntegerField(null=True)
    phone2 = models.IntegerField(null=True)
    phone3 = models.IntegerField(null=True)
    comment_phone1 = models.CharField(max_length=255,null=True)
    comment_phone2 = models.CharField(max_length=255,null=True)
    comment_phone3 = models.CharField(max_length=255,null=True)
    services = models.CharField(max_length=2000,null=True)
    shop = models.PositiveSmallIntegerField(null=True)
    shop_id = models.PositiveSmallIntegerField(null=True)
    status = models.CharField(max_length=255,null=True)
    ticket_paired = models.PositiveSmallIntegerField(null=True)
    type = models.CharField(max_length=255,null=True)
    type_id = models.PositiveSmallIntegerField(null=True)
    def __str__(self):
        return str(self.number)
class CallToday(models.Model):
    number = models.CharField(max_length=255, unique = True)
    fio = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    status = models.CharField(max_length=255)
    timer = models.CharField(max_length=255)
    workercode = models.IntegerField()
class Auth(models.Model):
    sell_code = models.CharField(max_length=255)
    operator = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
class DateTime(models.Model):
    datetime = models.CharField(max_length=2550)
    comments = models.CharField(max_length=2550)